name: Lumi APK Build

on:
  push:
    branches:
      - main  # или замени на твою ветку, например 'master'

jobs:
  build:
    name: Build Lumi APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17  # Или 11, если ты используешь другую версию

    - name: Grant permission to execute gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: lumi-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
